project_id = "nzisvnsrhzexmedzthyr"

[auth]
enabled = true
site_url = "https://mvp-gamma-orpin-38.vercel.app"
additional_redirect_urls = ["https://mvp-gamma-orpin-38.vercel.app"]
enable_signup = true
minimum_password_length = 8
password_requirements = "letters_digits"

[auth.email]
enable_signup = true
enable_confirmations = false
max_frequency = "1m"
otp_length = 8

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false
otp_length = 6
template = "Your code is {{ .Code }}"
max_frequency = "5s"

[storage.vector]
enabled = false
